version: "3"
services:
  nextjs:
    build: ./docker/
    container_name: nextjs-ts-jest-express
    ports:
      - "4001:3000"
    volumes:
      - ./app:/usr/src/app
    tty: true
    stdin_open: true
    command: "yarn dev"
